### ISSUE TITLE
Incorrect point number and elevation

### ISSUE THREAD

**Issue by mlt** [mlt/schwinn810#10]
It appears that point occupies only 2 bytes (thus making maximum of 65536 points) instead of 4 as [I assumed](https://github.com/mlt/schwinn810/wiki/Data-Format). There seems to be a case when word on offset 30 is different from 0.

**Comment by mlt** [comment]
@nc54 hold on with binary dump. I feel like I'm confident what needs to be fixed.

**Comment by nc54** [comment]
Deleted Linked file.  Used --debug with babelize.cmd not Download.exe

**Comment by nc54** [comment]
Deleted last one. Was the debug for babelize.  Use this one instead. Strange, they are the exact same size. https://dl.dropbox.com/u/19832238/schwinn810.bin

**Comment by mlt** [comment]
They have surprisingly different endings. I have no ideas what is transmitted in there after all points. Thank you.

**Comment by nc54** [comment]
Could this be added to the downloads? I believe the fix listed under the downloads was the first attempt to fix the problem.

**Comment by nc54** [comment]
I can confirm that % is showing properly and elevation is now correct.

**Comment by mlt** [comment]
I still don't know the proper size of both fields. I used to split 2 bytes for elevation and 4 for point #. Now it is 3/3. I'll make it 4/2 for the sake of simplicity. The only way to check proper size is to record a track of more than 65536 points which would last at least 36 hours, which is quite impossible given a batter life. Another alternative is to go above 2^24 cm = 167km which is also not quite possible. So I guess it does not matter.

**Comment by nc54** [comment]
There may be a way to record 36 hours by cracking open the watch and
splicing in another power supply -- something I'm not prepared to do.  

I guess I should say I assume the elevation is correct. I did not see any obvious problems.
On Sat, Jun 23, 2012 at 7:21 PM, Mikhail Titov <
reply@reply.github.com
