### ISSUE TITLE
no errors but not working

### ISSUE THREAD

**Issue by sandrovich** [mlt/schwinn810#28]
I'm having problems extracting data from my watch.
I bought that watch from french supermarket Carrefour and installed the driver as described in https://github.com/mlt/schwinn810/wiki/Windows 
The watch is detected and everything is fine but when I run download.exe --port COM3 the file waypoints.csv is empty.

The command output:
schwinn810  Copyright (C) 2012 Mikhail Titov

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under the terms of GPL-3 or later version.

WARNING:core.device:File a bug if you are not using Cresta or Mio watch!
Fetching track 0720101 [1/2] with 64 points
0%
Fetching track 0722101 [2/2] with 619 points
0%
16%
32%
48%
65%
81%
97%
Done

The file *.points has the information but the other one not. Could you help me?

**Comment by mlt** [comment]
> I run download.exe

Perhaps that win32 build is outdated. I uploaded [newer build](https://www.dropbox.com/sh/wc23kbxzr1s9jl1/wsbSSqzn7x/schwinn810). Try it.

**Comment by sandrovich** [comment]
Hello, I just test the new build and it worked. Now the problem is with the timezone, I changed the utc option in babelize, but it continue adding 5 hours to the time. I live in utc 0, so I try to remove the utc option with no luck. The time in .points is ok, but not in the tcx file.

Thank you

Edit: Ok, it is fixed. I added --tz Etc/Greenwich to the command for tcx files.

Great job, now I can export my workouts with all the information to web services like strava or endomondo.
One tip, for this watch without altimeter, upload first to strava to calculate altitude, and then export to gpx, this file contain the hr and altitude. Last, you can upload to endomondo without any problems.

**Comment by mlt** [comment]
Thanks for your feedback!

> I changed the utc option in babelize, but it continue adding 5 hours to the time

That setting affects gpsbabel only, i.e. makes proper timestamps in  GPX & KML. You fixed it the right way. Newer version will not rely on gpsbabel for GPX, and (TCX converter included) will default to GMT. Conversion from other time zone to Z time will be optional as discussed in #27.

> Great job, now I can export my workouts with all the information to web services like strava or endomondo.

As of now Strava exporter is not implemented with tcx2web :( A while ago they were accepting TCX submission by e-mail so one could added to `babelize` script a line calling command-line mailer. However things have changed. IIRC there is a draft Web API available... though I can't promise much about automatic uploads.

> One tip, for this watch without altimeter

There are numerous discussions on gis.stackexchange.com .Another option is to use http://www.gpsvisualizer.com/elevation
